//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class option_2Entities : DbContext
    {
        private static option_2Entities _context;

        public option_2Entities()
            : base("name=option_2Entities")
        {
        }
        
        public static option_2Entities GetContext()
        {
            if (_context == null)
                _context = new option_2Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<check_in> check_in { get; set; }
        public virtual DbSet<competition> competitions { get; set; }
        public virtual DbSet<horse> horses { get; set; }
        public virtual DbSet<horse_owner> horse_owner { get; set; }
        public virtual DbSet<jockey> jockeys { get; set; }
        public virtual DbSet<pair> pairs { get; set; }
        public virtual DbSet<participant> participants { get; set; }
    }
}
