//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class horse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public horse()
        {
            this.pairs = new HashSet<pair>();
        }
    
        public int id { get; set; }
        public int id_owner { get; set; }
        public string name_horse { get; set; }
        public string sex { get; set; }
        public Nullable<int> age { get; set; }

        public string owner_name
        {
            get
            {
                var owners = option_2Entities.GetContext().horse_owner.ToList();

                return owners.First(p => p.id == this.id_owner).name_owner;
            }
        }

        public virtual horse_owner horse_owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pair> pairs { get; set; }
    }
}
