//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class participant
    {
        public int id_pair { get; set; }
        public int id_check_in { get; set; }
        public Nullable<decimal> time_participants { get; set; }
        public Nullable<int> place_participants { get; set; }
    
        public virtual check_in check_in { get; set; }
        public virtual pair pair { get; set; }
    }
}
